# Assignment 5
## Data Preprocessing

We will be using a dataframe created from *Income Dirty Data.csv*. Download the file from D2L. 

1. Import the following modules
    - `pandas`
    - `numpy`
    - `preprocessing` from `sklearn` (for bonus question)
    - `KNNImputer` from `sklearn.impute` (for bonus question)
2. Create your dataframe from the file using `pandas`

In [2]:
import pandas as pd 
import numpy as np 
import sklearn as sl
from sklearn import preprocessing 
from sklearn.impute import KNNImputer

df = pd.read_csv("./Income Dirty Data.csv")

df.head(40)

    ID     sex  age    income  tax_15_pct
0    1   Women   21  147168.0    22075.20
1    2  Female   29  119595.0    17939.25
2    3  Female   56   87770.0    13165.50
3    4     NaN   21   54259.0     8138.85
4    5    Male   28       NaN   160230.00
5    6   Woman    0  128326.0    19248.90
6    7  Female   -1       NaN         NaN
7    8  Female   24       NaN    11820.60
8    9  Female   38  149473.0    22420.95
9   10     Man   48  113663.0  1136630.00
10  11   Woman   33   96649.0    14497.35
11  12    Male   55       NaN     9776.25
12  13     Man   52   64944.0     9741.60
13  14    Male   47   85300.0         NaN
14  15     Men   45   80091.0    12013.65
15  16   Women   25   56418.0     8462.70
16  17  Female   45   54189.0     8128.35
17  18    Male   29   67489.0    10123.35
18  19    Male   48  137978.0    20696.70
19  20  Female   -1   89991.0         NaN
20  21     Men   55  103803.0    15570.45
21  22  Female   20   59504.0     8925.60
22  23     Men   -1    -727.0    22500.00
23  24  Female   45  111069.0    16660.35
24  25    Male   52     239.0    10409.10
25  26    Male   26  116941.0    17541.15
26  27  Female   22   63018.0   252072.00
27  28     NaN   21   76019.0    11402.85
28  29   Women   43       NaN    16849.95
29  30   Woman   32   52020.0     7803.00
30  31    Male   59   75292.0    11293.80
31  32     NaN   23  148850.0    22327.50
32  33    Male   -1       NaN    19040.25
33  34    Male   60  148765.0         NaN
34  35     Man   43  128116.0    19217.40
35  36  Female   26     870.0    14330.40
36  37    Male   34   92533.0    13879.95
37  38    Male   57   96171.0    14425.65
38  39   Woman   48  107816.0    16172.40
39  40    Male   29  119538.0    17930.70

3. Calculate and display the following information
    - Total number of NaN values for **each column**
    - Percentage of NaN values in the dataset 
    - Number of rows *without* any NaN values

In [3]:

#NaN in each column 
null_values = (df.isna().sum())
print("Number of NaN per column")
print(null_values)


#% of Nan in dataset
print("\nPercentage of missing values:")
pct_missing = null_values.sum()/(len(df) * len(df.columns))
print(f"{pct_missing * 100:.2F}%")

#Number of rows without any Nan Values 
print("\nNumber of rows WITHOUT any missing values:")
rows_with_missing = len((df[(df.income.isna()) | (df.tax_15_pct.isna())]))
print(len(df) - rows_with_missing)

Number of NaN per column
ID              0
sex            88
age             0
income        109
tax_15_pct     93
dtype: int64

Percentage of missing values:
5.80%

Number of rows WITHOUT any missing values:
806

Besides missing values (NaN), the dataset contains errors. We have the following rules to check:

* All employees are adults (18+ years old)
* All employees pay 15% of their income for the tax
* All employees make money; no income should be <= 0 
---
4. Calculate and display the percentage of the data that does **NOT** violate any **one** of the rules.

In [4]:
# Code here
"""
pct_missing = null_values.sum()/(len(df) * len(df.columns))
print(f"{pct_missing * 100:.2F}%")
"""

valid_age = df["age"].ge(18)

valid_tax = df["income"]*0.15 == df["tax_15_pct"]

valid_income = df["income"].gt(0)

no_violation = valid_age & valid_tax & valid_income

percentage_no_violation = no_violation.sum()/ (len(df))

print(f"{percentage_no_violation * 100:.2F}%")

47.00%

Now that we have determined the number of erroneous datapoints in our set, let's work on correcting it as best we can.

5. Replace non *Female*/*Male* values in the **Sex** column with either *Female* or *Male* (e.g., Women --> Female)

In [5]:
# Code here
gender_map = {
    "Man":"Male", 
    "Men":"Male",
    "Woman": "Female", 
    "Women":"Female"
}


df["sex"] = df["sex"].replace(gender_map)
    #replace will run thorugh dictionary and replace all the values with the key '

df.head(20)

    ID     sex  age    income  tax_15_pct
0    1  Female   21  147168.0    22075.20
1    2  Female   29  119595.0    17939.25
2    3  Female   56   87770.0    13165.50
3    4     NaN   21   54259.0     8138.85
4    5    Male   28       NaN   160230.00
5    6  Female    0  128326.0    19248.90
6    7  Female   -1       NaN         NaN
7    8  Female   24       NaN    11820.60
8    9  Female   38  149473.0    22420.95
9   10    Male   48  113663.0  1136630.00
10  11  Female   33   96649.0    14497.35
11  12    Male   55       NaN     9776.25
12  13    Male   52   64944.0     9741.60
13  14    Male   47   85300.0         NaN
14  15    Male   45   80091.0    12013.65
15  16  Female   25   56418.0     8462.70
16  17  Female   45   54189.0     8128.35
17  18    Male   29   67489.0    10123.35
18  19    Male   48  137978.0    20696.70
19  20  Female   -1   89991.0         NaN

6. Replace non-positive **Age** values with NaN (`numpy.NaN`)
7. Replace non-positive **Income** values with NaN (`numpy.NaN`)
8. Replace non-positive **Tax (15%)** values with NaN (`numpy.NaN`)

In [6]:
# Code here
df["age"] = df["age"].where(df["age"].gt(0), np.nan)

df["income"] = df["income"].where(df["income"].gt(0), np.nan)

df["tax_15_pct"] = df["tax_15_pct"].where(df["tax_15_pct"].gt(0), np.nan)


df.head(25)

    ID     sex   age    income  tax_15_pct
0    1  Female  21.0  147168.0    22075.20
1    2  Female  29.0  119595.0    17939.25
2    3  Female  56.0   87770.0    13165.50
3    4     NaN  21.0   54259.0     8138.85
4    5    Male  28.0       NaN   160230.00
5    6  Female   NaN  128326.0    19248.90
6    7  Female   NaN       NaN         NaN
7    8  Female  24.0       NaN    11820.60
8    9  Female  38.0  149473.0    22420.95
9   10    Male  48.0  113663.0  1136630.00
10  11  Female  33.0   96649.0    14497.35
11  12    Male  55.0       NaN     9776.25
12  13    Male  52.0   64944.0     9741.60
13  14    Male  47.0   85300.0         NaN
14  15    Male  45.0   80091.0    12013.65
15  16  Female  25.0   56418.0     8462.70
16  17  Female  45.0   54189.0     8128.35
17  18    Male  29.0   67489.0    10123.35
18  19    Male  48.0  137978.0    20696.70
19  20  Female   NaN   89991.0         NaN
20  21    Male  55.0  103803.0    15570.45
21  22  Female  20.0   59504.0     8925.60
22  23    Male   NaN       NaN    22500.00
23  24  Female  45.0  111069.0    16660.35
24  25    Male  52.0     239.0    10409.10

The following question is a bonus (+10) question, but I'd encourage you to give it a try!

9. Use machine learning (`KNNImputer`) to impute all missing values (replaces NaN values with the most predicted values)
    - Will need to use a scaler and convert the values in the **Sex** column to a numeric value for algorithm to work properly
    - Show some of the data prior to imputing, and after imputing

In [ ]:
# I will attempt this one. I submitted the required stuff on D2L dropbox, but
#  will push this onto github if completed by 11:59

10. In the empty `Markdown` cell below, explain why it is important to clean a dataset before calculating analytics about the data

As we saw with this database, a lot of times datasets have negative values where negative values are not possible, or there is some simple humnan error in the data, like an extra 0 or a forgotten number. This could really skew things like the mean or the standard deviations. If we want to have meaningful analysis, we need to have accurate data.

10. Submit this `Jupyter` file to D2L, renamed as **Last_First_Assignment4.ipynb** 
    - Replace '**Last**' and '**First**' with your name